internal class CountryCode
{
    public string Name { get; set; }
    public string Code { get; set; }

    public static List<CountryCode> Values = new List<CountryCode>
    {
        new CountryCode { Name = "Afghanistan", Code = "93" },
        new CountryCode { Name = "Albania", Code = "355" },
        new CountryCode { Name = "Algeria", Code = "213" },
        new CountryCode { Name = "Andorra", Code = "376" },
        new CountryCode { Name = "Angola", Code = "244" },
        new CountryCode { Name = "Argentina", Code = "54" },
        new CountryCode { Name = "Armenia", Code = "374" },
        new CountryCode { Name = "Australia", Code = "61" },
        new CountryCode { Name = "Austria", Code = "43" },
        new CountryCode { Name = "Azerbaijan", Code = "994" },
        new CountryCode { Name = "Bahamas", Code = "1242" },
        new CountryCode { Name = "Bahrain", Code = "973" },
        new CountryCode { Name = "Bangladesh", Code = "880" },
        new CountryCode { Name = "Barbados", Code = "1246" },
        new CountryCode { Name = "Belarus", Code = "375" },
        new CountryCode { Name = "Belgium", Code = "32" },
        new CountryCode { Name = "Belize", Code = "501" },
        new CountryCode { Name = "Benin", Code = "229" },
        new CountryCode { Name = "Bhutan", Code = "975" },
        new CountryCode { Name = "Bolivia", Code = "591" },
        new CountryCode { Name = "Bosnia and Herzegovina", Code = "387" },
        new CountryCode { Name = "Botswana", Code = "267" },
        new CountryCode { Name = "Brazil", Code = "55" },
        new CountryCode { Name = "Brunei", Code = "673" },
        new CountryCode { Name = "Bulgaria", Code = "359" },
        new CountryCode { Name = "Burkina Faso", Code = "226" },
        new CountryCode { Name = "Burundi", Code = "257" },
        new CountryCode { Name = "Cabo Verde", Code = "238" },
        new CountryCode { Name = "Cambodia", Code = "855" },
        new CountryCode { Name = "Cameroon", Code = "237" },
        new CountryCode { Name = "Canada", Code = "1" },
        new CountryCode { Name = "Central African Republic", Code = "236" },
        new CountryCode { Name = "Chad", Code = "235" },
        new CountryCode { Name = "Chile", Code = "56" },
        new CountryCode { Name = "China", Code = "86" },
        new CountryCode { Name = "Colombia", Code = "57" },
        new CountryCode { Name = "Comoros", Code = "269" },
        new CountryCode { Name = "Congo (Congo-Brazzaville)", Code = "242" },
        new CountryCode { Name = "Costa Rica", Code = "506" },
        new CountryCode { Name = "Croatia", Code = "385" },
        new CountryCode { Name = "Cuba", Code = "53" },
        new CountryCode { Name = "Cyprus", Code = "357" },
        new CountryCode { Name = "Czech Republic", Code = "420" },
        new CountryCode { Name = "Denmark", Code = "45" },
        new CountryCode { Name = "Djibouti", Code = "253" },
        new CountryCode { Name = "Dominica", Code = "1767" },
        new CountryCode { Name = "Dominican Republic", Code = "1809" },
        new CountryCode { Name = "Ecuador", Code = "593" },
        new CountryCode { Name = "Egypt", Code = "20" },
        new CountryCode { Name = "El Salvador", Code = "503" },
        new CountryCode { Name = "Equatorial Guinea", Code = "240" },
        new CountryCode { Name = "Eritrea", Code = "291" },
        new CountryCode { Name = "Estonia", Code = "372" },
        new CountryCode { Name = "Eswatini", Code = "268" },
        new CountryCode { Name = "Ethiopia", Code = "251" },
        new CountryCode { Name = "Fiji", Code = "679" },
        new CountryCode { Name = "Finland", Code = "358" },
        new CountryCode { Name = "France", Code = "33" },
        new CountryCode { Name = "Gabon", Code = "241" },
        new CountryCode { Name = "Gambia", Code = "220" },
        new CountryCode { Name = "Georgia", Code = "995" },
        new CountryCode { Name = "Germany", Code = "49" },
        new CountryCode { Name = "Ghana", Code = "233" },
        new CountryCode { Name = "Greece", Code = "30" },
        new CountryCode { Name = "Grenada", Code = "1473" },
        new CountryCode { Name = "Guatemala", Code = "502" },
        new CountryCode { Name = "Guinea", Code = "224" },
        new CountryCode { Name = "Guinea-Bissau", Code = "245" },
        new CountryCode { Name = "Guyana", Code = "592" },
        new CountryCode { Name = "Haiti", Code = "509" },
        new CountryCode { Name = "Honduras", Code = "504" },
        new CountryCode { Name = "Hungary", Code = "36" },
        new CountryCode { Name = "Iceland", Code = "354" },
        new CountryCode { Name = "India", Code = "91" },
        new CountryCode { Name = "Indonesia", Code = "62" },
        new CountryCode { Name = "Iran", Code = "98" },
        new CountryCode { Name = "Iraq", Code = "964" },
        new CountryCode { Name = "Ireland", Code = "353" },
        new CountryCode { Name = "Israel", Code = "972" },
        new CountryCode { Name = "Italy", Code = "39" },
        new CountryCode { Name = "Ivory Coast", Code = "225" },
        new CountryCode { Name = "Jamaica", Code = "1876" },
        new CountryCode { Name = "Japan", Code = "81" },
        new CountryCode { Name = "Jordan", Code = "962" },
        new CountryCode { Name = "Kazakhstan", Code = "7" },
        new CountryCode { Name = "Kenya", Code = "254" },
        new CountryCode { Name = "Kiribati", Code = "686" },
        new CountryCode { Name = "Kuwait", Code = "965" },
        new CountryCode { Name = "Kyrgyzstan", Code = "996" },
        new CountryCode { Name = "Laos", Code = "856" },
        new CountryCode { Name = "Latvia", Code = "371" },
        new CountryCode { Name = "Lebanon", Code = "961" },
        new CountryCode { Name = "Lesotho", Code = "266" },
        new CountryCode { Name = "Liberia", Code = "231" },
        new CountryCode { Name = "Libya", Code = "218" },
        new CountryCode { Name = "Liechtenstein", Code = "423" },
        new CountryCode { Name = "Lithuania", Code = "370" },
        new CountryCode { Name = "Luxembourg", Code = "352" },
        new CountryCode { Name = "Madagascar", Code = "261" },
        new CountryCode { Name = "Malawi", Code = "265" },
        new CountryCode { Name = "Malaysia", Code = "60" },
        new CountryCode { Name = "Maldives", Code = "960" },
        new CountryCode { Name = "Mali", Code = "223" },
        new CountryCode { Name = "Malta", Code = "356" },
        new CountryCode { Name = "Marshall Islands", Code = "692" },
        new CountryCode { Name = "Mauritania", Code = "222" },
        new CountryCode { Name = "Mauritius", Code = "230" },
        new CountryCode { Name = "Mexico", Code = "52" },
        new CountryCode { Name = "Micronesia", Code = "691" },
        new CountryCode { Name = "Moldova", Code = "373" },
        new CountryCode { Name = "Monaco", Code = "377" },
        new CountryCode { Name = "Mongolia", Code = "976" },
        new CountryCode { Name = "Montenegro", Code = "382" },
        new CountryCode { Name = "Morocco", Code = "212" },
        new CountryCode { Name = "Mozambique", Code = "258" },
        new CountryCode { Name = "Myanmar (Burma)", Code = "95" },
        new CountryCode { Name = "Namibia", Code = "264" },
        new CountryCode { Name = "Nauru", Code = "674" },
        new CountryCode { Name = "Nepal", Code = "977" },
        new CountryCode { Name = "Netherlands", Code = "31" },
        new CountryCode { Name = "New Zealand", Code = "64" },
        new CountryCode { Name = "Nicaragua", Code = "505" },
        new CountryCode { Name = "Niger", Code = "227" },
        new CountryCode { Name = "Nigeria", Code = "234" },
        new CountryCode { Name = "North Korea", Code = "850" },
        new CountryCode { Name = "North Macedonia", Code = "389" },
        new CountryCode { Name = "Norway", Code = "47" },
        new CountryCode { Name = "Oman", Code = "968" },
        new CountryCode { Name = "Pakistan", Code = "92" },
        new CountryCode { Name = "Palau", Code = "680" },
        new CountryCode { Name = "Palestine", Code = "970" },
        new CountryCode { Name = "Panama", Code = "507" },
        new CountryCode { Name = "Papua New Guinea", Code = "675" },
        new CountryCode { Name = "Paraguay", Code = "595" },
        new CountryCode { Name = "Peru", Code = "51" },
        new CountryCode { Name = "Philippines", Code = "63" },
        new CountryCode { Name = "Poland", Code = "48" },
        new CountryCode { Name = "Portugal", Code = "351" },
        new CountryCode { Name = "Qatar", Code = "974" },
        new CountryCode { Name = "Romania", Code = "40" },
        new CountryCode { Name = "Russia", Code = "7" },
        new CountryCode { Name = "Rwanda", Code = "250" },
        new CountryCode { Name = "Saint Kitts and Nevis", Code = "1869" },
        new CountryCode { Name = "Saint Lucia", Code = "1758" },
        new CountryCode { Name = "Saint Vincent and the Grenadines", Code = "1784" },
        new CountryCode { Name = "Samoa", Code = "685" },
        new CountryCode { Name = "San Marino", Code = "378" },
        new CountryCode { Name = "Sao Tome and Principe", Code = "239" },
        new CountryCode { Name = "Saudi Arabia", Code = "966" },
        new CountryCode { Name = "Senegal", Code = "221" },
        new CountryCode { Name = "Serbia", Code = "381" },
        new CountryCode { Name = "Seychelles", Code = "248" },
        new CountryCode { Name = "Sierra Leone", Code = "232" },
        new CountryCode { Name = "Singapore", Code = "65" },
        new CountryCode { Name = "Slovakia", Code = "421" },
        new CountryCode { Name = "Slovenia", Code = "386" },
        new CountryCode { Name = "Solomon Islands", Code = "677" },
        new CountryCode { Name = "Somalia", Code = "252" },
        new CountryCode { Name = "South Africa", Code = "27" },
        new CountryCode { Name = "South Korea", Code = "82" },
        new CountryCode { Name = "South Sudan", Code = "211" },
        new CountryCode { Name = "Spain", Code = "34" },
        new CountryCode { Name = "Sri Lanka", Code = "94" },
        new CountryCode { Name = "Sudan", Code = "249" },
        new CountryCode { Name = "Suriname", Code = "597" },
        new CountryCode { Name = "Sweden", Code = "46" },
        new CountryCode { Name = "Switzerland", Code = "41" },
        new CountryCode { Name = "Syria", Code = "963" },
        new CountryCode { Name = "Taiwan", Code = "886" },
        new CountryCode { Name = "Tajikistan", Code = "992" },
        new CountryCode { Name = "Tanzania", Code = "255" },
        new CountryCode { Name = "Thailand", Code = "66" },
        new CountryCode { Name = "Timor-Leste", Code = "670" },
        new CountryCode { Name = "Togo", Code = "228" },
        new CountryCode { Name = "Tonga", Code = "676" },
        new CountryCode { Name = "Trinidad and Tobago", Code = "1868" },
        new CountryCode { Name = "Tunisia", Code = "216" },
        new CountryCode { Name = "Turkey", Code = "90" },
        new CountryCode { Name = "Turkmenistan", Code = "993" },
        new CountryCode { Name = "Tuvalu", Code = "688" },
        new CountryCode { Name = "Uganda", Code = "256" },
        new CountryCode { Name = "Ukraine", Code = "380" },
        new CountryCode { Name = "United Arab Emirates", Code = "971" },
        new CountryCode { Name = "United Kingdom", Code = "44" },
        new CountryCode { Name = "United States", Code = "1" },
        new CountryCode { Name = "Uruguay", Code = "598" },
        new CountryCode { Name = "Uzbekistan", Code = "998" },
        new CountryCode { Name = "Vanuatu", Code = "678" },
        new CountryCode { Name = "Vatican City (Holy See)", Code = "379" },
        new CountryCode { Name = "Venezuela", Code = "58" },
        new CountryCode { Name = "Vietnam", Code = "84" },
        new CountryCode { Name = "Yemen", Code = "967" },
        new CountryCode { Name = "Zambia", Code = "260" },
        new CountryCode { Name = "Zimbabwe", Code = "263" },
    };
}
